apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-with-configmap-volumes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: nginx:1.14.2
        name: nginx
        env:
        - name: __NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: __POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: __POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: __POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: __NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: __POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        ports:
        - containerPort: 80
        resources:
          requests: 
            cpu: 100m # 100 милли цпу - это 
            memory: 100Mi
          limits:
            cpu: 100m 
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d
        - name: podinfo
          mountPath: /etc/podinfo
      volumes:
      - name: config
        configMap:  
          name: my-configmap-2
      - name: podinfo
        downwardAPI:
          items:
            - path: "labels" # файл в который запишутся все labels из манифеста
              fieldRef:
                fieldPath: metadata.labels
            - path: "annotations" # файл в который запишутся все annotations из манифеста
              fieldRef:
                fieldPath: metadata.annotations
          