apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap-3
data:
  default.conf: |
    server {
      listen 80 default_server;
      server_name _;
      default_type text/plain;

      location / {
        return 200 'Hello it is $hostname\n';
      }
    }
